# Generated by Django 6.0.1 on 2026-01-08 23:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.PositiveIntegerField(help_text='Цена в центах (минимум 50 = $0.51)', validators=[django.core.validators.MinValueValidator(51)]),
        ),
    ]
